### ISSUE TITLE
Check out the script

### ISSUE THREAD

**Issue by sebastiandig** [USF-IMARS/BB3_processing#1]
Hey @7yl4r, I've posted the script with your suggestions. I still have a few problems with the erroneous data. 

It is currently writing the erroneous data in new files, which is what I want, but if the data fits the time format, and is significantly different time, it'll create a new file either way (what I don't want)

ex:
`09/28/19	17:32:50	470	2371	532	4130	650	4130	526`
`09/28/19	17:32:51	470	2351	532	4130	650	4130	526`
`09/28/19	17:17:33:08	470	2344	532	3965	650	4130	525`  <-- error
`09/28/19	17:33:09	470	2351	532	3988	650	4130	525`
`09/28/19	17:33:10	470	2361	532	4004	650	4130	525`
`09/28/19	17:33:12	470	2273	532	4026	650	4130	525`

line 3 will be read as 17:17:33, instead of being an error, so when doing the comparison, of `dt_new - dt_prev < timedelta(minute=5)` , it will create a new file, when I would rather it make it an exception and add it to the same file.

**Comment by 7yl4r** [comment]
For this specific issue I would suggest changing how you chop up the line on l17:

```
        time_of_sample = line_of_text[0:17]
```

Instead of grabbing the first 18 characters, you might try splitting the line up by the spaces.

```
# split up the line into a list
columns = line_of_text.split(" ")
# use just the first two
first_two_cols = columns[0:1]
# join them back together so you can use strptime
datetime_string = "{} {}".format(first_two_cols[0], first_two_cols[1])
```

You could put that all together into a one liner.

However, for file parsing I think you want to use something like [pandas.DataFrame.from_csv](http://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.DataFrame.from_csv.html?highlight=from_csv#pandas.DataFrame.from_csv) (using ' ' as sep) or the [parse module](https://pypi.org/project/parse/) to parse the lines using format strings.

**Comment by 7yl4r** [comment]
For the lines above a parse format string might be:

`{:2d}/{:2d}/{:2d} {:2d}:{:2d}:{:2d} {:3d} {:4d} {:3d} {:4d} {:3d} {:4d} {:4d}`

**Comment by 7yl4r** [comment]
this section

```
        for dtt in line_of_text:
            try:
                dt = datetime.strptime(time_of_sample, dt_fmt)
            except Exception:                                   #the errors involves looping the error 46 times, then continuing
                #print(line)
                #newfile = open('files_with_errors.txt', "a")
                #newfile.write(line)
                continue
```

loops through each character in `line_of_text` which is what is causing your multiple errors printing.
I think you want to remove the for loop entirely so that the continue bumps up to the while loop.

However, since you do `line_of_text = f.readline()` at the end of the while loop we need to do that before the continue so it doesn't loop infinitely.

**Comment by sebastiandig** [comment]
I've looked over the suggestions. The new line parse would definitely work better. I am trying to test it out on my local computer, but I'm having errors with importing parse.

`Traceback (most recent call last):
  File "C:/Users/sebastian/Documents/Cruise_docs/Seabird/tester.py", line 5, in <module>
    from parse import parse`
`ModuleNotFoundError: No module named 'parse'`

I don't know how the try and except will change if remove the `for loop`. Without changing how it is parsed, removing the loop will cause it to infinitely loop the except. i'm hoping by changing to the parse, the for loop will not loop 46 times even.

**Comment by 7yl4r** [comment]
You will need to do a `line_of_text = f.readline()` before you `continue` to prevent the infinite loop.

**Comment by sebastiandig** [comment]
Adding the `line_of_text` seemed to fix the looping error when removing the `for loop`.

I finally figured out why I couldn't use `import parse`. I attempted to use it and received this error: 
`parsed_line[0], parsed_line[1], parsed_line[2],`
`TypeError: 'NoneType' object is not subscriptable`

Whenever the parse runs, it seems like no variables are being read. 

`parsed_line = parse(line_fmt, line_of_text)`
`print(parsed_line)`
Result: `None`

I looked at the type of characters and they are all str, so I changed the `{:2d}` to `{:2w}`, but that didn't help either.

**Comment by sebastiandig** [comment]
@7yl4r 
I figured out the parsing issue. I've added another file called `BB3_separator_revised.py` due to the major edits I did in PyCharm. I'm not sure how to pull your request into the original, but I took most of the edits into the revised version. I hope it looks better.

**Comment by 7yl4r** [comment]
Looking good! Is it working?
